name: BWPlugin
author: Rafael Auler
main: me.rafaelauler.ss.BukkitMain
version: 1.0
loadbefore: [KPCore]
depend: [ProtocolLib]
softdepend: [AuraSkills, yPlugins]
commands:
  set-prefix:
  pickencantar:
  creport:
  modo:
  sudo:
  consolesudo:
  manutencao:
  ctag:
  dano:
  grupo:
  tempogrupo:
  jogarbw:
  lobby:
  gorankup:
  perfil:
  
  
  
  
  
  
  
  
  