name: Impact-ServerController
author: Ebenezer7
main: me.rafaelauler.ss.BukkitMain
version: 1.0
loadbefore: [KPCore]
depend: [ProtocolLib]
softdepend: [AuraSkills, yPlugins]
commands:
  set-prefix:
  pickencantar:
  report:
  adquirirvip:
  modo:
  sudo:
  consolesudo:
  manutencao:
  ctag:
  dano:
  grupo:
  tempogrupo:
  tag:
  
  
  
  
  
  
  
  